apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "platform-testing.fullname" . }}-dm
  labels:
    app: {{ template "platform-testing.name" . }}
    chart: {{ template "platform-testing.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: "{{.Values.schedule}}"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ template "platform-testing.name" . }}
            release: {{ .Release.Name }}
        spec:
          restartPolicy: Never
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                - "python3"
                - "monitor.py"
                - "--plugin"
                - "dm_blackbox"
                - "--display"
                - "--postjson"
                - "http://{{.Release.Name}}-console-backend-data-logger:3001/metrics"
                - "--extra"
                - "--dmendpoint http://{{.Release.Name}}-deployment-manager:5000"
